# Step 1: Use an official Node.js runtime as a parent image
FROM node:20
ENV YARN_CACHE_FOLDER=/cache/yarn

# Step 2: Set the working directory inside the container to /app
WORKDIR /app

# Step 3: Copy package.json and package-lock.json (or yarn.lock)
COPY package.json yarn.lock ./

# Step 4: Install dependencies
RUN --mount=type=cache,target=/cache/yarn \
  yarn install

# Step 5: Bundle app source inside Docker image
COPY . .

# Step 7: Define the command to run the app
CMD ["yarn", "dev"]
