version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - go-modules:/go/pkg/mod
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}
      - REDIS_URI=redis://redis:6379

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME} # Pass the variable to the container
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD} # Pass the variable to the container
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data:
  go-modules: # Cache for Go modules to speed up builds
