version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./app:/app # Mount the local app directory to the container
      - go-modules:/go/pkg/mod # Cache Go modules
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data:
  go-modules: # Cache for Go modules to speed up builds
