version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - go-modules:/go/pkg/mod
    ports:
      - "8080:8080"
      
  frontend:
    build: ./verden-frontend
    volumes:
      - ./verden-frontend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
      - "35729:35729"


  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data:
  go-modules: # Cache for Go modules to speed up builds
