version: '3.8'
services:
  backend:
    build: ./backend
    image: verden-backend:latest  # Descriptive tag for the backend image
    volumes:
      - ./backend:/app
      - go-modules:/go/pkg/mod
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}
      - REDIS_URI=redis:6379
      - CORS_ORIGIN=http://localhost:5173

  frontend:
    build: ./frontend
    image: verden-frontend:latest  # Descriptive tag for the frontend image
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js # Mount the init script
    env_file: ./mongodb/.env-mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data:
  go-modules: # Cache for Go modules to speed up builds
